exclude: '.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        name: black
        entry: poetry run black scbs

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.256"
    hooks:
      - id: ruff
        exclude: "benchmarks"